version: '3.4'

networks:
  agent_network:
    driver: overlay
    attachable: true
  gateway:
    external:
      name: lbgateway

volumes:
  portainer:
    driver: glusterfs
    driver_opts:
      servers: localhost
    name: "portainer"

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - portainer:/data
    networks:
      - agent_network
      - gateway
    deploy:
      mode: replicated
      replicas: 1

visualizer:
  image: dockersamples/visualizer:stable
  ports:
    - target: 8080
      published: 8000
      protocol: tcp
      mode: ingress
  stop_grace_period: 1m30s
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  deploy:
    placement:
      constraints: [node.role == manager]


