route:
  receiver: 'test-team'
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

receivers:
  - name: 'test-team'
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: 'Prometheus'
        channel: 'server_monitoring'
        api_url: 'https://hooks.slack.com/services/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'