[[servers]]
host = "192.168.0.218"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "MAF\\%s"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=maf,dc=local"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"